apiVersion: v1
kind: Service
metadata:
  name: js-example-service
  namespace: js-example-ns
  labels:
    app: js-example-app
spec:
  selector:
    app: js-example-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80