apiVersion: v1
kind: Service
metadata:
  name: js-example-linux-service
  namespace: js-example-ns
  labels:
    app: js-example
spec:
  selector:
    app: js-example-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080