apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-example-deployment
  namespace: js-example-ns
  labels:
    app: js-example-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: js-example-app
  template:
    metadata:
      labels:
        app: js-example-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: js-example-container
        image: ghcr.io/boardjnky4/js-example:latest
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.4"
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: Always
