apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-example-deployment
  namespace: js-example-ns
  labels:
    app: js-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
  spec:
    containers:
    - name: js-example
      image: ghcr.io/boardjnky4/js-example:latest
        imagePullPolicy: Always
      ports:
      - containerPort: 80
    imagePullSecrets:
    - name: github-registry